/**
 * Pulls the study list from the Google Sheet into data/studies.json at BUILD
 * time, so the API key never reaches the browser.
 *
 * The current pharmatiya.net homepage embeds the sheet ID and API key in
 * client-side JavaScript on a public page, which means anyone viewing source
 * can read and use the key. Fetching at build time removes that exposure and
 * also makes the search instant, with no network round-trip for the visitor.
 *
 * Usage:
 *   GOOGLE_SHEETS_API_KEY=... PHARMATIYA_SHEET_ID=... npm run studies
 *
 * Pharmatiya keeps editing the same spreadsheet; re-run this (or let CI run
 * it) to publish changes.
 */

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const apiKey = process.env.GOOGLE_SHEETS_API_KEY;
const sheetId = process.env.PHARMATIYA_SHEET_ID;
const range = process.env.PHARMATIYA_SHEET_RANGE || "studylist!A1:Z1000";

if (!apiKey || !sheetId) {
  console.error(
    "Missing GOOGLE_SHEETS_API_KEY or PHARMATIYA_SHEET_ID.\n" +
      "Set both and re-run. data/studies.json is left unchanged.",
  );
  process.exit(1);
}

/** Column positions, taken from the existing site's own display logic. */
const COLUMN = {
  details: 2, // C — Study Details
  link: 3, // D — More...
  dataType: 5, // F — Type of Data
  dataSource: 6, // G — Data Source
};

const url =
  `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}` +
  `/values/${encodeURIComponent(range)}?key=${apiKey}`;

const response = await fetch(url);

if (!response.ok) {
  console.error(`Sheets API returned ${response.status} ${response.statusText}`);
  process.exit(1);
}

const payload = await response.json();
const rows = payload.values ?? [];

if (rows.length < 2) {
  console.error("Sheet returned no data rows. Nothing written.");
  process.exit(1);
}

const cell = (row, index) => (row[index] ?? "").toString().trim();

const studies = rows
  .slice(1)
  .map((row, index) => ({
    id: `s${index + 1}`,
    details: cell(row, COLUMN.details),
    link: cell(row, COLUMN.link),
    dataType: cell(row, COLUMN.dataType),
    dataSource: cell(row, COLUMN.dataSource),
  }))
  // A row with no description is not a study record.
  .filter((study) => study.details.length > 0);

const outPath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "data",
  "studies.json",
);

await writeFile(
  outPath,
  JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      source: "Google Sheet — studylist tab",
      note: "Generated by scripts/fetch-studies.mjs. Do not edit by hand.",
      studies,
    },
    null,
    2,
  ) + "\n",
  "utf8",
);

console.log(`Wrote ${studies.length} studies to data/studies.json`);
